// ============================================================
// DATA DUMMY - Sistem Bimbingan Skripsi
// ============================================================

export const dummyUsers = [
  {
    id: "u1",
    email: "budi.santoso@univ.ac.id",
    full_name: "Dr. Budi Santoso, M.Kom",
    role: "dosen",
    nip: "198501012010011001",
    program_studi: "Teknik Informatika",
    status: "active",
  },
  {
    id: "u2",
    email: "sari.dewi@univ.ac.id",
    full_name: "Dr. Sari Dewi, M.T",
    role: "dosen",
    nip: "198703152012012002",
    program_studi: "Teknik Informatika",
    status: "active",
  },
  {
    id: "u3",
    email: "ahmad.fauzi@univ.ac.id",
    full_name: "Prof. Ahmad Fauzi, Ph.D",
    role: "dosen",
    nip: "197012011998031003",
    program_studi: "Sistem Informasi",
    status: "active",
  },
  {
    id: "u4",
    email: "reza.pratama@mhs.univ.ac.id",
    full_name: "Reza Pratama",
    role: "mahasiswa",
    nim: "2021010001",
    program_studi: "Teknik Informatika",
    status: "active",
  },
  {
    id: "u5",
    email: "dina.maharani@mhs.univ.ac.id",
    full_name: "Dina Maharani",
    role: "mahasiswa",
    nim: "2021010002",
    program_studi: "Teknik Informatika",
    status: "active",
  },
  {
    id: "u6",
    email: "fajar.nugroho@mhs.univ.ac.id",
    full_name: "Fajar Nugroho",
    role: "mahasiswa",
    nim: "2021010003",
    program_studi: "Teknik Informatika",
    status: "active",
  },
  {
    id: "u7",
    email: "laila.putri@mhs.univ.ac.id",
    full_name: "Laila Putri Anggraini",
    role: "mahasiswa",
    nim: "2021010004",
    program_studi: "Sistem Informasi",
    status: "active",
  },
  {
    id: "u8",
    email: "hendra.wijaya@mhs.univ.ac.id",
    full_name: "Hendra Wijaya",
    role: "mahasiswa",
    nim: "2020010005",
    program_studi: "Teknik Informatika",
    status: "cuti",
  },
  {
    id: "u9",
    email: "admin@univ.ac.id",
    full_name: "Administrator Sistem",
    role: "admin",
    program_studi: "",
    status: "active",
  },
];

export const dummyPeriods = [
  {
    id: "p1",
    name: "Semester Genap 2025/2026",
    start_date: "2026-02-01",
    end_date: "2026-07-31",
    is_active: true,
    description: "Periode bimbingan skripsi semester genap",
    created_date: "2026-01-15",
  },
  {
    id: "p2",
    name: "Semester Ganjil 2025/2026",
    start_date: "2025-08-01",
    end_date: "2026-01-31",
    is_active: false,
    description: "Periode bimbingan skripsi semester ganjil",
    created_date: "2025-07-10",
  },
  {
    id: "p3",
    name: "Semester Genap 2024/2025",
    start_date: "2025-02-01",
    end_date: "2025-07-31",
    is_active: false,
    description: "Periode bimbingan skripsi semester genap",
    created_date: "2025-01-20",
  },
];

export const dummyMappings = [
  {
    id: "m1",
    student_email: "reza.pratama@mhs.univ.ac.id",
    student_name: "Reza Pratama",
    student_nim: "2021010001",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    period_id: "p1",
    thesis_title:
      "Implementasi Machine Learning untuk Deteksi Fraud pada Transaksi Digital",
    status: "active",
  },
  {
    id: "m2",
    student_email: "dina.maharani@mhs.univ.ac.id",
    student_name: "Dina Maharani",
    student_nim: "2021010002",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    period_id: "p1",
    thesis_title: "Sistem Rekomendasi Konten Berbasis Collaborative Filtering",
    status: "active",
  },
  {
    id: "m3",
    student_email: "fajar.nugroho@mhs.univ.ac.id",
    student_name: "Fajar Nugroho",
    student_nim: "2021010003",
    supervisor_email: "sari.dewi@univ.ac.id",
    supervisor_name: "Dr. Sari Dewi, M.T",
    period_id: "p1",
    thesis_title: "Pengembangan Aplikasi IoT untuk Smart Home Monitoring",
    status: "active",
  },
  {
    id: "m4",
    student_email: "laila.putri@mhs.univ.ac.id",
    student_name: "Laila Putri Anggraini",
    student_nim: "2021010004",
    supervisor_email: "ahmad.fauzi@univ.ac.id",
    supervisor_name: "Prof. Ahmad Fauzi, Ph.D",
    period_id: "p1",
    thesis_title: "Analisis Sentimen Media Sosial dengan Deep Learning",
    status: "active",
  },
  {
    id: "m5",
    student_email: "hendra.wijaya@mhs.univ.ac.id",
    student_name: "Hendra Wijaya",
    student_nim: "2020010005",
    supervisor_email: "sari.dewi@univ.ac.id",
    supervisor_name: "Dr. Sari Dewi, M.T",
    period_id: "p1",
    thesis_title: "Optimasi Algoritma Routing pada Jaringan SDN",
    status: "active",
  },
];

export const dummyBookings = [
  {
    id: "b1",
    student_email: "reza.pratama@mhs.univ.ac.id",
    student_name: "Reza Pratama",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s1",
    date: "2026-05-08",
    start_time: "09:00",
    end_time: "10:00",
    mode: "offline",
    location: "Ruang Dosen B201",
    status: "pending",
    notes: "Ingin diskusi mengenai BAB 2 metodologi penelitian",
    period_id: "p1",
    created_date: "2026-05-05",
  },
  {
    id: "b2",
    student_email: "dina.maharani@mhs.univ.ac.id",
    student_name: "Dina Maharani",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s2",
    date: "2026-05-09",
    start_time: "10:00",
    end_time: "11:00",
    mode: "online",
    location: "https://meet.google.com/abc-def-ghi",
    status: "pending",
    notes: "Revisi BAB 3 dan dataset preprocessing",
    period_id: "p1",
    created_date: "2026-05-04",
  },
  {
    id: "b3",
    student_email: "reza.pratama@mhs.univ.ac.id",
    student_name: "Reza Pratama",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s3",
    date: "2026-04-25",
    start_time: "09:00",
    end_time: "10:00",
    mode: "offline",
    location: "Ruang Dosen B201",
    status: "approved",
    notes: "Konsultasi kerangka teori",
    period_id: "p1",
    created_date: "2026-04-20",
  },
  {
    id: "b4",
    student_email: "dina.maharani@mhs.univ.ac.id",
    student_name: "Dina Maharani",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s4",
    date: "2026-04-18",
    start_time: "10:00",
    end_time: "11:00",
    mode: "online",
    location: "https://meet.google.com/xyz",
    status: "completed",
    notes: "Presentasi BAB 1",
    period_id: "p1",
    created_date: "2026-04-12",
  },
  {
    id: "b5",
    student_email: "reza.pratama@mhs.univ.ac.id",
    student_name: "Reza Pratama",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s5",
    date: "2026-04-10",
    start_time: "09:00",
    end_time: "10:00",
    mode: "offline",
    location: "Ruang Dosen B201",
    status: "completed",
    notes: "Review proposal awal",
    period_id: "p1",
    created_date: "2026-04-05",
  },
  {
    id: "b6",
    student_email: "fajar.nugroho@mhs.univ.ac.id",
    student_name: "Fajar Nugroho",
    supervisor_email: "sari.dewi@univ.ac.id",
    supervisor_name: "Dr. Sari Dewi, M.T",
    slot_id: "s6",
    date: "2026-05-07",
    start_time: "13:00",
    end_time: "14:00",
    mode: "offline",
    location: "Laboratorium IoT",
    status: "approved",
    notes: "Demo prototype sensor",
    period_id: "p1",
    created_date: "2026-05-02",
  },
  {
    id: "b7",
    student_email: "laila.putri@mhs.univ.ac.id",
    student_name: "Laila Putri Anggraini",
    supervisor_email: "ahmad.fauzi@univ.ac.id",
    supervisor_name: "Prof. Ahmad Fauzi, Ph.D",
    slot_id: "s7",
    date: "2026-04-30",
    start_time: "14:00",
    end_time: "15:00",
    mode: "online",
    location: "https://zoom.us/j/12345",
    status: "completed",
    notes: "Review model LSTM",
    period_id: "p1",
    created_date: "2026-04-24",
  },
  {
    id: "b8",
    student_email: "hendra.wijaya@mhs.univ.ac.id",
    student_name: "Hendra Wijaya",
    supervisor_email: "sari.dewi@univ.ac.id",
    supervisor_name: "Dr. Sari Dewi, M.T",
    slot_id: "s8",
    date: "2026-03-15",
    start_time: "13:00",
    end_time: "14:00",
    mode: "offline",
    location: "Laboratorium Jaringan",
    status: "completed",
    notes: "Diskusi topologi jaringan",
    period_id: "p1",
    created_date: "2026-03-10",
  },
  {
    id: "b9",
    student_email: "reza.pratama@mhs.univ.ac.id",
    student_name: "Reza Pratama",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s9",
    date: "2026-03-20",
    start_time: "09:00",
    end_time: "10:00",
    mode: "offline",
    location: "Ruang Dosen B201",
    status: "rejected",
    reject_reason: "Dokumen belum lengkap, harap lengkapi dulu",
    period_id: "p1",
    created_date: "2026-03-18",
  },
  {
    id: "b10",
    student_email: "dina.maharani@mhs.univ.ac.id",
    student_name: "Dina Maharani",
    supervisor_email: "budi.santoso@univ.ac.id",
    supervisor_name: "Dr. Budi Santoso, M.Kom",
    slot_id: "s10",
    date: "2026-04-02",
    start_time: "10:00",
    end_time: "11:00",
    mode: "online",
    location: "https://meet.google.com/aaa",
    status: "completed",
    notes: "Review hasil eksperimen",
    period_id: "p1",
    created_date: "2026-03-28",
  },
];

export const dummySlots = [
  {
    id: "s_new1",
    supervisor_email: "budi.santoso@univ.ac.id",
    date: "2026-05-10",
    start_time: "09:00",
    end_time: "10:00",
    max_students: 1,
    current_bookings: 0,
    mode: "offline",
    location: "Ruang Dosen B201",
    period_id: "p1",
    is_available: true,
  },
  {
    id: "s_new2",
    supervisor_email: "budi.santoso@univ.ac.id",
    date: "2026-05-10",
    start_time: "10:00",
    end_time: "11:00",
    max_students: 1,
    current_bookings: 0,
    mode: "online",
    location: "https://meet.google.com/budi-slot",
    period_id: "p1",
    is_available: true,
  },
  {
    id: "s_new3",
    supervisor_email: "budi.santoso@univ.ac.id",
    date: "2026-05-14",
    start_time: "13:00",
    end_time: "14:00",
    max_students: 2,
    current_bookings: 0,
    mode: "offline",
    location: "Ruang Dosen B201",
    period_id: "p1",
    is_available: true,
  },
  {
    id: "s_new4",
    supervisor_email: "sari.dewi@univ.ac.id",
    date: "2026-05-12",
    start_time: "09:00",
    end_time: "10:00",
    max_students: 1,
    current_bookings: 0,
    mode: "offline",
    location: "Lab IoT Lt. 3",
    period_id: "p1",
    is_available: true,
  },
  {
    id: "s_new5",
    supervisor_email: "ahmad.fauzi@univ.ac.id",
    date: "2026-05-13",
    start_time: "14:00",
    end_time: "15:00",
    max_students: 1,
    current_bookings: 0,
    mode: "online",
    location: "https://zoom.us/j/fauzi",
    period_id: "p1",
    is_available: true,
  },
];

export const dummyLogs = [
  {
    id: "l1",
    booking_id: "b5",
    student_email: "reza.pratama@mhs.univ.ac.id",
    supervisor_email: "budi.santoso@univ.ac.id",
    date: "2026-04-10",
    summary:
      "Mahasiswa mempresentasikan proposal awal. Struktur penelitian sudah cukup baik namun perlu diperkuat pada bagian latar belakang masalah.",
    revisions:
      "Perbaiki latar belakang dengan data pendukung yang lebih kuat. Tambahkan referensi terbaru (2022-2025).",
    next_steps: "Revisi BAB 1 dan kirim ke pembimbing sebelum 17 April",
    progress_percentage: 25,
    validated_by_supervisor: true,
  },
  {
    id: "l2",
    booking_id: "b4",
    student_email: "dina.maharani@mhs.univ.ac.id",
    supervisor_email: "budi.santoso@univ.ac.id",
    date: "2026-04-18",
    summary:
      "Presentasi BAB 1 berjalan lancar. Rumusan masalah sudah jelas dan terarah.",
    revisions:
      "Perbaiki penulisan hipotesis penelitian. Tambahkan batasan penelitian yang lebih spesifik.",
    next_steps:
      "Mulai BAB 2 - Tinjauan Pustaka, fokus pada algoritma collaborative filtering",
    progress_percentage: 30,
    validated_by_supervisor: true,
  },
  {
    id: "l3",
    booking_id: "b7",
    student_email: "laila.putri@mhs.univ.ac.id",
    supervisor_email: "ahmad.fauzi@univ.ac.id",
    date: "2026-04-30",
    summary:
      "Review model LSTM sudah dilakukan. Akurasi model mencapai 87% pada dataset uji.",
    revisions:
      "Coba tambahkan layer dropout untuk mengurangi overfitting. Eksperimen dengan berbagai window size.",
    next_steps:
      "Jalankan eksperimen dengan 5 konfigurasi berbeda dan dokumentasikan hasilnya",
    progress_percentage: 65,
    validated_by_supervisor: true,
  },
  {
    id: "l4",
    booking_id: "b8",
    student_email: "hendra.wijaya@mhs.univ.ac.id",
    supervisor_email: "sari.dewi@univ.ac.id",
    date: "2026-03-15",
    summary:
      "Diskusi topologi jaringan SDN. Mahasiswa sudah memahami konsep dasar SDN controller.",
    revisions:
      "Pelajari lebih dalam tentang OpenFlow protocol. Siapkan testbed di GNS3.",
    next_steps: "Implementasi topologi dasar dan dokumentasikan dalam BAB 3",
    progress_percentage: 40,
    validated_by_supervisor: false,
  },
  {
    id: "l5",
    booking_id: "b10",
    student_email: "dina.maharani@mhs.univ.ac.id",
    supervisor_email: "budi.santoso@univ.ac.id",
    date: "2026-04-02",
    summary:
      "Review hasil eksperimen collaborative filtering. Precision dan recall sudah memenuhi target.",
    revisions:
      "Tambahkan evaluasi menggunakan metrik NDCG. Bandingkan dengan baseline model.",
    next_steps: "Selesaikan BAB 4 dan siapkan draft BAB 5",
    progress_percentage: 55,
    validated_by_supervisor: true,
  },
];

export const dummyActivityLogs = [
  {
    id: "al1",
    actor_email: "admin@univ.ac.id",
    actor_name: "Administrator Sistem",
    actor_role: "admin",
    action: "create_mapping",
    description:
      "Admin menjodohkan Reza Pratama dengan Dr. Budi Santoso, M.Kom",
    target_type: "mapping",
    target_id: "m1",
    created_date: "2026-02-05T08:30:00Z",
  },
  {
    id: "al2",
    actor_email: "admin@univ.ac.id",
    actor_name: "Administrator Sistem",
    actor_role: "admin",
    action: "create_mapping",
    description:
      "Admin menjodohkan Dina Maharani dengan Dr. Budi Santoso, M.Kom",
    target_type: "mapping",
    target_id: "m2",
    created_date: "2026-02-05T08:45:00Z",
  },
  {
    id: "al3",
    actor_email: "reza.pratama@mhs.univ.ac.id",
    actor_name: "Reza Pratama",
    actor_role: "mahasiswa",
    action: "create_booking",
    description: "Mahasiswa membuat booking bimbingan untuk tanggal 8 Mei 2026",
    target_type: "booking",
    target_id: "b1",
    created_date: "2026-05-05T09:15:00Z",
  },
  {
    id: "al4",
    actor_email: "budi.santoso@univ.ac.id",
    actor_name: "Dr. Budi Santoso, M.Kom",
    actor_role: "dosen",
    action: "approved_booking",
    description:
      "Dr. Budi Santoso, M.Kom disetujui bimbingan Dina Maharani tanggal 18 April 2026",
    target_type: "booking",
    target_id: "b4",
    created_date: "2026-04-15T10:00:00Z",
  },
  {
    id: "al5",
    actor_email: "budi.santoso@univ.ac.id",
    actor_name: "Dr. Budi Santoso, M.Kom",
    actor_role: "dosen",
    action: "create_slot",
    description:
      "Dosen menambahkan slot ketersediaan tanggal 10 Mei 2026 pukul 09:00-10:00",
    target_type: "slot",
    target_id: "s_new1",
    created_date: "2026-05-03T14:20:00Z",
  },
  {
    id: "al6",
    actor_email: "budi.santoso@univ.ac.id",
    actor_name: "Dr. Budi Santoso, M.Kom",
    actor_role: "dosen",
    action: "rejected_booking",
    description:
      "Dr. Budi Santoso menolak bimbingan Reza Pratama tanggal 20 Maret 2026",
    target_type: "booking",
    target_id: "b9",
    created_date: "2026-03-19T11:30:00Z",
  },
  {
    id: "al7",
    actor_email: "admin@univ.ac.id",
    actor_name: "Administrator Sistem",
    actor_role: "admin",
    action: "activate_period",
    description: 'Admin mengaktifkan periode "Semester Genap 2025/2026"',
    target_type: "period",
    target_id: "p1",
    created_date: "2026-02-01T07:00:00Z",
  },
  {
    id: "al8",
    actor_email: "dina.maharani@mhs.univ.ac.id",
    actor_name: "Dina Maharani",
    actor_role: "mahasiswa",
    action: "create_booking",
    description: "Mahasiswa membuat booking bimbingan untuk tanggal 9 Mei 2026",
    target_type: "booking",
    target_id: "b2",
    created_date: "2026-05-04T16:45:00Z",
  },
  {
    id: "al9",
    actor_email: "admin@univ.ac.id",
    actor_name: "Administrator Sistem",
    actor_role: "admin",
    action: "update_user",
    description: "Admin mengubah data user Hendra Wijaya (status: cuti)",
    target_type: "user",
    target_id: "u8",
    created_date: "2026-03-01T09:00:00Z",
  },
  {
    id: "al10",
    actor_email: "fajar.nugroho@mhs.univ.ac.id",
    actor_name: "Fajar Nugroho",
    actor_role: "mahasiswa",
    action: "cancel_booking",
    description: "Mahasiswa membatalkan booking bimbingan tanggal 1 Mei 2026",
    target_type: "booking",
    target_id: "b6",
    created_date: "2026-04-29T13:00:00Z",
  },
];

export const dummyNotifications = [
  {
    id: "n1",
    recipient_email: "reza.pratama@mhs.univ.ac.id",
    title: "Bimbingan Disetujui",
    message:
      "Pengajuan bimbingan Anda pada 25 Apr 2026 telah disetujui oleh Dr. Budi Santoso",
    type: "booking_approved",
    is_read: true,
    created_date: "2026-04-21T10:00:00Z",
  },
  {
    id: "n2",
    recipient_email: "reza.pratama@mhs.univ.ac.id",
    title: "Bimbingan Ditolak",
    message:
      "Pengajuan bimbingan Anda pada 20 Mar 2026 ditolak. Alasan: Dokumen belum lengkap",
    type: "booking_rejected",
    is_read: true,
    created_date: "2026-03-19T11:30:00Z",
  },
  {
    id: "n3",
    recipient_email: "dina.maharani@mhs.univ.ac.id",
    title: "Bimbingan Disetujui",
    message: "Pengajuan bimbingan Anda pada 18 Apr 2026 telah disetujui",
    type: "booking_approved",
    is_read: false,
    created_date: "2026-04-15T10:00:00Z",
  },
  {
    id: "n4",
    recipient_email: "budi.santoso@univ.ac.id",
    title: "Permintaan Bimbingan Baru",
    message: "Reza Pratama mengajukan bimbingan untuk tanggal 8 Mei 2026",
    type: "booking_new",
    is_read: false,
    created_date: "2026-05-05T09:15:00Z",
  },
  {
    id: "n5",
    recipient_email: "budi.santoso@univ.ac.id",
    title: "Permintaan Bimbingan Baru",
    message: "Dina Maharani mengajukan bimbingan untuk tanggal 9 Mei 2026",
    type: "booking_new",
    is_read: false,
    created_date: "2026-05-04T16:45:00Z",
  },
];
